apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access_key
              name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: minio
        image: minio/minio:latest
        imagePullPolicy: Always
        name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: artemis
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: ClusterIP
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio
  namespace: artemis
data:
  access_key: <changeme>
  secret_key: <changeme>
